[build]
  base = "landing"
  command = "npm run build"
  publish = "landing/.next"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"
